name: Security Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'A message to greet the user'
        required: true
        type: string
        default: 'Hello, World!'
      hadolint_enabled:
        description: 'Whether hadolint is enabled'
        required: false
        type: boolean
        default: true
      trufflehog_enabled:
        description: 'Whether trufflehog is enabled'
        required: false
        type: boolean
        default: true

jobs:
  security-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Greet User
      run: |
        echo ${{ inputs.message }}
        ls -lR .github Dockerfile

    - name: Hadolint Dockerfile Linting 
      uses: hadolint/hadolint-action@v3.1.0
      if: ${{ inputs.hadolint_enabled }}
      with:
        dockerfile: Dockerfile

    - name: TruffleHog OSS
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      if: ${{ inputs.trufflehog_enabled }}
      with:
        path: ./
        base: "${{ github.event.repository.default_branch }}"
        head: HEAD
        extra_args: --debug --results=verified,unknown
    # - name: Secret Scanner
    #   uses: secret-scanner/action@0.0.2
    #   if: ${{ inputs.trufflehog_enabled }}
