name: Security Workflow

on:
  workflow_call:
    inputs:
      message:
        description: 'A message to greet the user'
        required: true
        type: string
        default: 'Hello, World!'
      hadolint_enabled:
        description: 'Whether hadolint is enabled'
        required: false
        type: boolean
        default: true
      trufflehog_enabled:
        description: 'Whether trufflehog is enabled'
        required: false
        type: boolean
        default: true

jobs:
  security-workflow:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Greet User
      run: |
        echo ${{ inputs.message }}
        ls -lR .github Dockerfile

    - uses: hadolint/hadolint-action@v3.1.0
      if: ${{ inputs.hadolint_enabled }}
      with:
        dockerfile: Dockerfile

    - uses: max/secret-scan@master
    if: ${{ inputs.trufflehog_enabled }}

